language: node_js
node_js:
- '0.12'
sudo: false
cache:
  directories:
    - "node_modules"
    - "phantom"
before_install:
- npm config set spin false
- npm install -g npm@^2
- mkdir -p $PWD/phantom
- curl --output $PWD/phantom/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1
- chmod a+x $PWD/phantom/phantomjs
- phantomjs --version
- export PATH=$PWD/phantom:$PATH
- phantomjs --version
install:
- npm install -g bower
- npm install
- bower install
script:
- npm test
env:
  global:
  - PHANTOMJS=$PWD/phantom/phantomjs
deploy:
  provider: releases
  before_deploy: "make binarios"
  api_key:
    secure: huGK5wrkmFa2k2gySV71RUriYlh3NrVuxtSp6sBBOadJu7exfy/+vILyEH3JWcJHhphcmAlMvkNEt2PqUHSTXuYVAJnGtitCyXJpvbYrSQaAHjkN4wNxEYe8nIjIYUbZ/NlxhOh7bZiF/HfLV5wEj8o2SWNHbSM9upGgRnQjn1Y=
  file: 
    - "binarios/conectar-educativo-osx32.zip"
    - "binarios/conectar-educativo-win32.zip"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
